name = "writerly_parser"
version = "1.0.0"

[dependencies]
blamedlines = { "path" = "../blamedlines" }
vxml_parser = { "path" = "../vxml_parser" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
