name = "writerly_parser"
version = "1.0.0"

[dependencies]
blamedlines = { git = "git@github.com:vistuleB/blamedlines", ref = "583ddcf" }
vxml_parser = { git = "git@github.com:vistuleB/vxml_parser", ref = "7ef7d21" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
