name = "writerly"
version = "1.0.0"

[dependencies]
blamedlines = { "path" = "../blamedlines" }
vxml = { "path" = "../vxml" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
